### ISSUE TITLE
Meeting - 2014-10-27

### ISSUE THREAD

**Issue by Seberius** [renodevelopers/meetups#42]
One week until the next meeting.  This issue is to confirm who will be giving talks at the next meeting and confirm the schedule.  Please be aware that Hack4Reno will be taking place the weekend just _before_ the meeting.
#### Meeting Presentations:

I have listed the topics where people suggested a topic they could cover and were asked to do /volunteered for October, along with a link to the issue where possible.  If you are listed please let us know if you will be able to do the presentation this month, and if so, the duration (you can do that below or in the original issue).  We may not be able to fit all of them depending on duration, so one or two may need to be pushed back to November or later.
- [x] @ErikCH - Ember.js presentation #38 - ?? min - **Moved to November**
- [x] @elskwid - Unit Testing presentation - ?? min - **Moved to later date**
- [x] @Seberius - Karma/Jasmine lightning talk #40 - 10 min - **Confirmed**
- [x] @HMUDesign - Three.js (WebGL) presentation #25 - 10 to 30 min - **Confirmed**

If there are any I have missed please let me know.  There are a few other topics that have been suggested without a current presentation date that we can sort through once we have this month completed.
#### Upcoming events:

**Hack4Reno** - http://hack4reno.com/ - Oct 25 - 26 - This will take place before the next meeting, so if you are interested in participating and have not coordinated with your group you should do so this week.
